name: 'Slack Notify'
description: "Slack Notification action that doesn't suck"
branding:
  icon: 'slack'
  color: 'purple'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  channel:
    description: TODO
    default: ''
    required: false
  username:
    description: TODO
    default: ''
    required: false
  icon_emoji:
    description: TODO
    default: ''
    required: false
  icon_url:
    description: TODO
    default: ''
    required: false
  text:
    description: TODO
    default: ''
    required: false
# fields:
#   description: TODO
#   default: ''
#   required: false
# status:
#   description: TODO
#   default: ''
#   required: false
# custom_payload:
#   description: TODO
#   required: false
# mention:
#   description: TODO
#   default: ''
#   required: false
